# Generated by Django 4.2.1 on 2023-08-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=-2008, upload_to='Gallery'),
            preserve_default=False,
        ),
    ]
